apiVersion: apps/v1
kind: Deployment
metadata:
  name: task4-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task4
  template:
    metadata:
      labels:
        app: task4
    spec:
      containers:
      - name: task4
        image: task4:local
        ports:
        - containerPort: 5000